title: "Indradip's Portfolio"
description: "A personal portfolio to showcase my work and skills."
url: "https://indradiproy133.github.io/portfolio"  # Leave as it is for GitHub Pages
theme: jekyll-theme-cayman  # This can be your chosen template name

# Customize further settings like logo, social media, etc.

